# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-04 12:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20160604_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='chat_id',
            field=models.CharField(blank=True, max_length=255, verbose_name='Chat Id'),
        ),
        migrations.AddField(
            model_name='user',
            name='message_id',
            field=models.CharField(blank=True, max_length=255, verbose_name='Message Id'),
        ),
    ]
