# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-04 05:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('diller', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255, verbose_name='Name of Product')),
                ('price', models.PositiveIntegerField(verbose_name='Price')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantity')),
                ('diller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_dillers', to='diller.Diller', verbose_name='Product diller')),
            ],
        ),
    ]
