# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 20:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name of User')),
                ('phone', models.CharField(max_length=255, verbose_name='Phone')),
                ('address', models.ManyToManyField(db_table='diller_addresses', related_name='addresses', to='address.Address')),
            ],
        ),
    ]
