# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-04 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diller', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diller',
            name='airport',
            field=models.CharField(blank=True, max_length=255, verbose_name='Airport'),
        ),
    ]
